name: Hello World
description: Greet someone and record the time

inputs:
  who-to-greet:
    description: 'Chi salutare'
    required: true
    default: 'World'


outputs:
   time: # id of output
    description: The time we greeted you

runs:
  using: node20
  main: dist/index.js
